Add recordingActive option to setUrl
luanpotter/audioplayers pull request #634
Opened 2020-09-22 07:00 UTC by reedom

In our use case, we need to have the `recordingActive` option to `setUrl`, which is currently only available with `play`, not to break our coexistent microphone feature.

BTW, `play` seemed to have a better way of passing parameters to the native layers so that I've derived it for `setUrl`.

2020-09-23 03:05 UTC, luanpotter requested changes
This is wrong. setUrl should not even have a respectSilence flag. setUrl means set url. we can have a setRecordingActive method, set RespectSilence, etc.

play is a helper method that takes in a lot of params, calls setUrl, etc and then call resume

2020-09-23 03:58 UTC, reedom commented
In that case, is it possible not to init the `AVAudioSession`, specifically not to call `AVAudioSession:setCategory` during `setUrl`?
I'm not sure yet but possibly calling it with `AVAudioSessionCategoryPlayback` may collapse the running microphone functionality.

2020-09-23 04:02 UTC, reedom commented
Or it'd be nice the init done with that `setRecordingActive`'s state respectedly.

2020-09-23 04:25 UTC, luanpotter commented
I see what you mean. I will try to see if there is a way, we might need to concede to this solution due to how the native side works. One thing though, don't you need to change the native side of setUrl to receive the param anyway?

I'm not super familiar with ios shenanigans but what should happen ideally is:

* setUrl **just** sets the url, does not do anything yet. It might actually load the audio. download the file, put it in memory. but it does not start playing so it should not mess with the microphone.
* play/resume then start playing, that is when the mic could be collapsed.

But it seems by what you say that our pre loading of the audio on iOS is causing the mic problem :/

2020-09-23 04:34 UTC, reedom commented
I'm familiar with iOS programming but not with audio not so much yet,
but anyway, it seems what `setUrl` does is to call `AVPlayerItem: initWithURL`
https://github.com/luanpotter/audioplayers/blob/master/darwin/Classes/AudioplayersPlugin.m#L546
and in advance it inits the audio session.
https://github.com/luanpotter/audioplayers/blob/master/darwin/Classes/AudioplayersPlugin.m#L517
If it is okay to postpone the init, we can go that way.

2020-09-23 04:39 UTC, reedom commented
Oh, sorry.

| One thing though, don't you need to change the native side of setUrl to receive the param anyway?
There was no need to change, when I tested with the modification 👍

2020-09-24 00:21 UTC, reedom commented
Now I think it might be nice to split `setUrl` into two independant functions:
- Setting up the audio environment/attributes
- rest of content management part
This makes less handy though, preferable for developers who want to have more control in hand.

2021-03-18 03:19 UTC, luanpotter commented
yes, I 100% agree. In fact I want to improve it even more:
https://github.com/luanpotter/audioplayers/issues/724
I will take a look at this after I release 0.18.0

2021-04-10 14:54 UTC, erickzanardo commented
This PR is quite outdated and haven't got updates in a long time. Closing this. If the author wants to continue working on this, just lets us know and we can re open the PR.

2021-04-10 14:54 UTC, closed without merging